# Generated by Django 5.1.4 on 2025-01-04 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="portinfo",
            options={"verbose_name": "港口信息", "verbose_name_plural": "港口信息"},
        ),
        migrations.AlterField(
            model_name="portinfo",
            name="port_id",
            field=models.CharField(
                max_length=20,
                primary_key=True,
                serialize=False,
                verbose_name="港口编号",
            ),
        ),
        migrations.AlterField(
            model_name="voyageinfo",
            name="end_time",
            field=models.DateTimeField(default=0, verbose_name="结束时间"),
        ),
        migrations.AlterField(
            model_name="voyageinfo",
            name="start_time",
            field=models.DateTimeField(unique=True, verbose_name="开始时间"),
        ),
    ]
