# Generated by Django 5.1.4 on 2025-01-04 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0002_alter_portinfo_options_alter_portinfo_port_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shipinfo",
            name="ship_id",
            field=models.CharField(
                max_length=20,
                primary_key=True,
                serialize=False,
                verbose_name="船舶呼号",
            ),
        ),
    ]
