# Generated by Django 5.1.4 on 2025-01-04 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0003_alter_shipinfo_ship_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="marineweather",
            old_name="latitude",
            new_name="weather_latitude",
        ),
        migrations.RenameField(
            model_name="marineweather",
            old_name="longitude",
            new_name="weather_longitude",
        ),
        migrations.RenameField(
            model_name="marineweather",
            old_name="timestamp",
            new_name="weather_timestamp",
        ),
    ]
