# Generated by Django 5.1.4 on 2025-01-04 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0004_rename_latitude_marineweather_weather_latitude_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dockedship",
            name="leave_time",
            field=models.DateTimeField(blank=True, null=True, verbose_name="离港时间"),
        ),
    ]
