# Generated by Django 5.1.4 on 2025-01-04 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0005_alter_dockedship_leave_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voyageinfo",
            name="end_time",
            field=models.DateTimeField(
                blank=True, default=0, null=True, verbose_name="结束时间"
            ),
        ),
    ]
